### ISSUE TITLE
images not shown if base uri exist

### ISSUE THREAD

**Issue by proguard** [oleh-v/prestashop-module-promotional-stickers-free#1]
Hi,

Love your promotional stickers, we noticed that if there is a base uri, images are not shown in either config or product page.

in promostickers.php, had to change line 863 to $html = '<img src="..' . DIRECTORY_SEPARATOR . 'modules/'.  before images showed in config

Also on line 417 removed __ps_base_uri from  $img[$key]['picture'] = _PS_BASE_URL_ . __PS_BASE_URI__ . _MODULE_DIR_ . $this->name

it doubles up the base uri in the url  etc. http://example.com/mybaseuri//mybaseuri/modules/promotionalstickers/views.....

**Comment by oleh-v** [comment]
Got it. Thank you!
